# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fdf8aff05ecefc4fbb0a66166fa367d5cb4d59a311a44886893db1aa9663642597d4fd50c9795724f407c3faabb7a42effe2bf177280df1c36f80b2aae9edc2
  twitter_app_id: <%= ENV["TWITTER_APP_ID"] %>
  twitter_app_secret: <%= ENV["TWITTER_APP_ID"] %>


test:
  secret_key_base: 71daedf227b58d10eb71e07270f74b522fd99f1d046f031d18771fe7728c835c575760ddda611d5c2b45089076e6cd2cc154e770fa777f5eac4976475ae8d99f
  twitter_app_id: <%= ENV["TWITTER_APP_ID"] %>
  twitter_app_secret: <%= ENV["TWITTER_APP_ID"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
